### ISSUE TITLE
can't filter search for submachine guns?

### ISSUE THREAD

**Issue by wkearney99** [dswistowski/itemmanager-issues#1]
It won't find submachine guns.  Can't find based on just 'su' or 'gun', and not on 'submachine'

It'll allow searching for just about everything else, just won't find submachine guns.

**Comment by dswistowski** [comment]
It's possible to filter by subtype now
![image](https://user-images.githubusercontent.com/197861/31047604-cb51ffbc-a605-11e7-9aec-3872a7b715a1.png)
